### ISSUE TITLE
建议修改的 obsidian-plugin-proxy 插件单独整个项目

### ISSUE THREAD

**Issue by leic4u** [gslnzfq/obsidian-proxy-server#1]
并且加上开源协议，上游项目为 [MIT](https://github.com/binyu1231/obsidian-plugin-proxy/blob/v0.0.1/LICENSE) License ，协议还是比较宽松的。

**Comment by gslnzfq** [comment]
> 并且加上开源协议，上游项目为 [MIT](https://github.com/binyu1231/obsidian-plugin-proxy/blob/v0.0.1/LICENSE) License ，协议还是比较宽松的，更加宽松一点。

其实插件修改后，更新不需要太频繁就没有单独提出来。

**Comment by leic4u** [comment]
卧槽，我在说什么。。。比较宽松的，更加宽松一点。。。。。不好意思，已更正。

> 其实插件修改后，更新不需要太频繁就没有单独提出来。

主要是因为 [MIT](https://github.com/binyu1231/obsidian-plugin-proxy/blob/v0.0.1/LICENSE) License 要求下游项目要保留原作者的许可信息。为了合情合理合法，建议单独整一个。

**Comment by gslnzfq** [comment]
已fork仓库做了些修改，仓库地址 https://github.com/gslnzfq/obsidian-plugin-proxy

**Comment by leic4u** [comment]
感谢开发者，已为 https://github.com/gslnzfq/obsidian-plugin-proxy 献上第一个 star
